# This is a basic workflow to help you get started with Actions

name: PROD Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main"]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: scratchOrgDevelopBranch
        # Fetch all history commit
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '20'
      # Install the SFDX CLI using the npm command
    - name: Install the SFDX CLI
      run: |
          npm install @salesforce/cli --global
          sf --help

    - name: Install SFDX & SFDX Git Delta
      run: |
        npm install sfdx-cli@7.209.6
        echo y | node_modules/sfdx-cli/bin/run plugins:install sfdx-git-delta
    - name: Org Authorization
      run: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out server.key -base64 -K DE3B4F6346E0CFA95CA695168A0FD8DA4D06AE808A0AFA9A4DBD2502D5DD6FE7 -iv AC767FEDCF2105140E84B62495C3F43A


    - name: Generate package.xml
      run: |
        #Generate package.xml between the current branch & 
        node_modules/sfdx-cli/bin/run sgd:source:delta --to "HEAD" --from "HEAD~1" --output .
        # Install xmlstarlet
        sudo apt-get install -y xmlstarlet

        # Set the version in package.xml to 59.0
        xmlstarlet ed --inplace -u "/Package/version" -v "59.0" package/package.xml

        cat package/package.xml
        cat destructiveChanges/destructiveChanges.xml

    - name: Authenticate to Salesforce using JWT
      env:
        SF_CONSUMER_KEY: "3MVG9GCMQoQ6rpzR1iIJ_5t2.L.MZtBh6YpZKeMoB2UZd8R9V5zjlsjBuRAfUlgpab4Sozm3Rpx8QzwVdq.8K"
        SF_USER_NAME: "arunachalam98@kap.com"
        SF_PRIVATE_KEY: 
            "-----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEAwnT1H1VGK8AVZjuhYf7U5WCby9xHEFyoz2j0enFIUxjBi7TQ
            HpdiRIFDL6tdCpCo2zQ1Mlk/PpzJwVGSv1jYbiaNUssrYCjL5ZnvZIA8Wtpp0G5u
            Gt0wS1sD3h78br2AI7nbcjASKsE+wWIOGT0iTfjODNtW2BHVs1pF2/KB2rajehhQ
            f3TppjoTA/3L2/nAuveGd9FxjywuXZ0GVOxya0gj0zF9Qrh4Li7rgLIOLthyt9XE
            2TPyczTUzcjBP44Dt21gz+f2PcIVol0qFLpriMlnfCNtDjy3jqZKR/vvUXWpUQK9
            /9WyPf0V42lB78lVda0/vF8zQmWp9zLKOlx84wIDAQABAoIBAQCmzZ7KruJPeyig
            Fnyby/WhgRqDZ8QJtAIWUKiOM4hfx3eWuJZh92eS7fLM/EkGXAqMZh9PviCzO9kR
            HEEuJC8bZbSKlb7ycGxe2onwgtPC92IXKfMG1j+sFDmgGqJc9+7oNnCYZcXfqP6E
            8fC4E6nOiqNtgeTf2YSfocsVHdPn4IxD/6pySKDxh9bBramaB8t1rhHrdJU3UmVP
            s4Qu5t3KEpekWabh0GeitKZO0mGi5otiJxyrAy9Np2pLLWW39JsYBW2ypOcMXVg7
            OOGDhNljfKE4vRN4/uDcWi+WerLN/nCIjXuLDE03DM3x2BxMSB8tRIigousIYf4b
            wnpo44spAoGBAPehWASRGnzn8QCXCVUOGLlv3Zl+2kWibdcKsY5qUifXv02O0QtS
            +rTU2YR9zk/60DhdZshrYh9kSo1ERApGxedKQgqVIOAj0I94f5h3hfk7k9ubuXRA
            w9iJVSPsw7QHZ4eIXoiSwpEyJVGHIBDn551HjYr8WG6eAcs/RAoDwH4tAoGBAMkH
            hfu/kBE60ZfTiT1Lv5HSYx7VhD6lVAxi7C3pNqyWcCb4MMw7OAoJbVUbtGCDL2cg
            nvqrsCABF1W13VPHmpmuEBfD2S4OvUabvc6wBiTgbHwLxhI4tSQh6h7qvpXJun6q
            0+eSeu5t6uXCcM8MwJotlnubxEjPTOAubttpUOFPAoGBAK+/mgl7tpHpx9lEWMI+
            A/wwUdVr+5wqYMybcVMDUJWogMSZ1PG1jeujmVF4PGH1P6yRVa5u0DA5bNQAHE4y
            1qiFwoNiPff2U0JQIjbitXoi95iIWEIS6SyYo42gr3DpRGgjt/w0NNT6AxRu06pL
            /M1aiDGZUWYIzHskxrRY31htAoGAIIuZQ2KF/mQZXo0eoM/Mmd0Hsww6NrIpYz/4
            oI4rDdHlIkn4DHhh4C4ahzbPAvj6CaYcVtTI1MWYc4XX6SJdgxfM/yvz0yMLvYyl
            M/sHY5z5szNsw7JukQT0lEDIzhM0oCEj4U+zmzosVzodbUfRPqS2whg7tNXqyjh6
            Ngdc0r0CgYAH341k4LPrVjzNphfzfHkQj57BeADZXG/ytwagKzNnt3LSVDp5csI/
            UcKq1cEeEnTS82vNLEn2k5uLNnzf5sRLT3G0wBDoP8s5d4HpY/KCgfV5ao1UHlyi
            Zrz7GaNux0WRGy80DmRTsIfTxkepO4xTpHy3tDt64O4mjYprClhttg==
            -----END RSA PRIVATE KEY-----"
      run: |
          echo "${SF_PRIVATE_KEY}" > server.key
          sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USER_NAME --setdefaultdevhubusername


       # sf org login jwt --client-id 3MVG9GCMQoQ6rpzR1iIJ_5t2.L.MZtBh6YpZKeMoB2UZd8R9V5zjlsjBuRAfUlgpab4Sozm3Rpx8QzwVdq.8K --jwt-key-file assets/server.key --username arunachalam98@kap.com --set-default --alias HubOrg --instance-url https://login.salesforce.com
   
      
    - name: Deployement to PROD
      run: |
        node_modules/sfdx-cli/bin/run force:source:deploy -x package/package.xml -u PROD
 