# This is a basic workflow to help you get started with Actions

name: PROD Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main"]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: scratchOrgDevelopBranch
        # Fetch all history commit
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install SFDX & SFDX Git Delta
      run: |
        npm install sfdx-cli@7.209.6
        echo y | node_modules/sfdx-cli/bin/run plugins:install sfdx-git-delta
    - name: Org Authorization
      run: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out server.key -base64 -K DE3B4F6346E0CFA95CA695168A0FD8DA4D06AE808A0AFA9A4DBD2502D5DD6FE7 -iv AC767FEDCF2105140E84B62495C3F43A


    - name: Generate package.xml
      run: |
        #Generate package.xml between the current branch & 
        node_modules/sfdx-cli/bin/run sgd:source:delta --to "HEAD" --from "HEAD~1" --output .
        # Install xmlstarlet
        sudo apt-get install -y xmlstarlet

        # Set the version in package.xml to 59.0
        xmlstarlet ed --inplace -u "/Package/version" -v "59.0" package/package.xml

        cat package/package.xml
        cat destructiveChanges/destructiveChanges.xml

    - name: Authentication to PROD 
      run: node_modules/sfdx-cli/bin/run auth:jwt:grant  --clientid=3MVG9GCMQoQ6rpzR1iIJ_5t2.L5sskzNvBe4XZ.nqdSV7h0UNBNzFg7v3yK0a.BRLL8VhIbV88HrrdVnOLzIm --username=arunachalam98@kap.com --jwtkeyfile server.key --setalias=PROD

    - name: Deployement to PROD
      run: |
        node_modules/sfdx-cli/bin/run force:source:deploy -x package/package.xml -u PROD
 
