name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: salesforcecli/sfdx-actions/setup@v1
        with:
          version: latest

      - name: Authenticate to Salesforce using JWT
        env:
          SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
          SF_USER_NAME: ${{ secrets.SF_USER_NAME }}
          SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
        run: |
          echo "${SF_PRIVATE_KEY}" > server.key
          sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USER_NAME --setdefaultdevhubusername

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app/main/default
          sfdx force:source:deploy -p manifest/package.xml
          sfdx force:apex:test:run --resultformat human --codecoverage --outputdir test-results --testlevel RunLocalTests
